sudo: false
language: generic
deploy:
  provider: gcs
  access_key_id: GOOGA6ETINWIQ6FJT6KH
  secret_access_key:
    secure: ZGgvgYp2syyM47zaWfyKrYmQU4RfTOrfBP4NNyEZmvwGy1uKkE/k9b3JbJgOVcEb10wk3Ts0c45m76DmpaoZgqdFHvF4tUrCS2rjyd7XvViB7M7V/dumcBeCcvg5ARcHUWCmWVtGOCmwDS/xTlSschlCDOL8AAfGThypUnji91nhHqo+MQJoGFjS/tdkcNYuHOzcZXdCQFULD0455zIaeHeDuWTlRUNc04hpTNMp8EjeVYpUL08CXZ0xDKk+zu+/6VxsU4mxI61qCp2wJIbUyrR/82JP7Vh0NRtT38RoQGdUxW1C+jWw+Ddh57ilOOxZrE/3ol3FxQsSruZpBbd/waG4BmwnJZGAHILQvZmqiK3ntTIBKCOqA5UpIVhfFKkxcPD1UjGKkFyNXQNZy94UE7jC5Ifmp2BfKb9K3d9vMA98roUUWUhfZDhfT0jTCGuQD4wHySqMC9YIxsEGCd6zJ7BzhRROSncioYHRICH0VK41TsCPr9ve/6jiJ/gmwl330yRJWKqwJXFB9m7W/MJUOFcNuYS7a6E23AnAJjDW53mqqkTaTRqo8Db3LNqc4WfbsmV0iD1/xOzJ3BILfGcy53zd5xuELjbdN1625wBohUzKgii7hVbDBuLSLQRijHEnTD3CSojiXcrDpo4axWH7IcHwlqS45VpnhNW7p9I3ms0=
  bucket: www.samginn.com
  skip_cleanup: true
  on:
    repo: samginn/samginn.com
